# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculate_weights <- function(z, X) {
    .Call('VIPER_calculate_weights', PACKAGE = 'VIPER', z, X)
}

fitting_lasso <- function(y, X, min, alpha) {
    .Call('VIPER_fitting_lasso', PACKAGE = 'VIPER', y, X, min, alpha)
}

log_factorial <- function(Y) {
    .Call('VIPER_log_factorial', PACKAGE = 'VIPER', Y)
}

log_factorial_calculated <- function(N) {
    .Call('VIPER_log_factorial_calculated', PACKAGE = 'VIPER', N)
}

reweighting_sum_C <- function(Ymat, Yflagmat, Y, Yflag, prior_weight, ImputeAll) {
    .Call('VIPER_reweighting_sum_C', PACKAGE = 'VIPER', Ymat, Yflagmat, Y, Yflag, prior_weight, ImputeAll)
}

reweighting_C <- function(Ymat, Yflagmat, Y, Yflag) {
    .Call('VIPER_reweighting_C', PACKAGE = 'VIPER', Ymat, Yflagmat, Y, Yflag)
}

imputation_by_samples <- function(data, selected_logxx, logxx, zero_matrix, n, p, minbool, alpha) {
    .Call('VIPER_imputation_by_samples', PACKAGE = 'VIPER', data, selected_logxx, logxx, zero_matrix, n, p, minbool, alpha)
}

replacing_by_expectation_C <- function(Ymat, Yflagmat, Y, Yflag, Ymat_sub, Yflagmat_sub, prior_weight, ImputeAll) {
    .Call('VIPER_replacing_by_expectation_C', PACKAGE = 'VIPER', Ymat, Yflagmat, Y, Yflag, Ymat_sub, Yflagmat_sub, prior_weight, ImputeAll)
}

imputation_by_samples_expectation <- function(data, selected_logxx, logxx, zero_matrix, n, p, minbool, alpha) {
    .Call('VIPER_imputation_by_samples_expectation', PACKAGE = 'VIPER', data, selected_logxx, logxx, zero_matrix, n, p, minbool, alpha)
}

